### ISSUE TITLE
Opvragen van concepten geeft 500 voor JSON (html werkt wel)

### ISSUE THREAD

**Issue by vancamti** [OnroerendErfgoed/skosprovider#110]
@JonasGe commented on [Tue Jan 11 2022](https://github.com/OnroerendErfgoed/thesaurus/issues/224)

Bvb. https://thesaurus.onroerenderfgoed.be/conceptschemes/GEBEURTENISTYPES/c?ctype=concept&label=sy&language=

**Comment by vancamti** [comment]
```
2022-01-11 14:04:36,762 ERROR [thesaurus.exception_views][MainThread] 'NoneType' object has no attribute 'format'
Traceback (most recent call last):
  File "/var/projects/thesaurus/venv/lib/python3.6/site-packages/pyramid/tweens.py", line 41, in excview_tween
    response = handler(request)
  File "/var/projects/thesaurus/venv/lib/python3.6/site-packages/pyramid/router.py", line 144, in handle_request
    registry, request, context, context_iface, view_name
  File "/var/projects/thesaurus/venv/lib/python3.6/site-packages/pyramid/view.py", line 674, in _call_view
    response = view_callable(context, request)
  File "/var/projects/thesaurus/venv/lib/python3.6/site-packages/pyramid/config/views.py", line 170, in attr_view
    return view(context, request)
  File "/var/projects/thesaurus/venv/lib/python3.6/site-packages/pyramid/config/views.py", line 196, in predicate_wrapper
    return view(context, request)
  File "/var/projects/thesaurus/venv/lib/python3.6/site-packages/pyramid/viewderivers.py", line 427, in rendered_view
    result = view(context, request)
  File "/var/projects/thesaurus/venv/lib/python3.6/site-packages/pyramid/viewderivers.py", line 113, in _class_requestonly_view
    response = getattr(inst, attr)()
  File "/var/projects/thesaurus/venv/lib/python3.6/site-packages/pyramid_skosprovider/views.py", line 272, in get_conceptscheme_concepts
    concepts = provider.find(query, **kwargs)
  File "/var/projects/thesaurus/venv/lib/python3.6/site-packages/skosprovider_sqlalchemy/providers.py", line 292, in find
    return [self._get_id_and_label(c, lan) for c in self._sort(all, sort, lan, sort_order=='desc')]
  File "/var/projects/thesaurus/venv/lib/python3.6/site-packages/skosprovider_sqlalchemy/providers.py", line 292, in <listcomp>
    return [self._get_id_and_label(c, lan) for c in self._sort(all, sort, lan, sort_order=='desc')]
  File "/var/projects/thesaurus/venv/lib/python3.6/site-packages/skosprovider_sqlalchemy/providers.py", line 230, in _get_id_and_label
    l = c.label(lan)
  File "/var/projects/thesaurus/venv/lib/python3.6/site-packages/skosprovider_sqlalchemy/models.py", line 212, in label
    return skoslabel(self.labels, language)
  File "/var/projects/thesaurus/venv/lib/python3.6/site-packages/skosprovider/skos.py", line 542, in label
    l = find_best_label_for_type(labels, lang, 'prefLabel')
  File "/var/projects/thesaurus/venv/lib/python3.6/site-packages/skosprovider/skos.py", line 566, in find_best_label_for_type
    inexact = filter_labels_by_language(typelabels, language, True)
  File "/var/projects/thesaurus/venv/lib/python3.6/site-packages/skosprovider/skos.py", line 584, in filter_labels_by_language
    language = tags.tag(language).language.format
AttributeError: 'NoneType' object has no attribute 'format'
```
